# Generated by Django 5.1.1 on 2024-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_book_customer_order_delete_pupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='asdasd', upload_to='book-images/'),
            preserve_default=False,
        ),
    ]
