# Generated by Django 5.1.1 on 2024-09-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
